version: '3'
services:
  gstreamer:
    build:
      dockerfile: docker/arm64v8/Dockerfile
      context: .
    volumes:
      - ./:/home/Projects/
    working_dir: /home/Projects/
    entrypoint:
      - /bin/bash
